/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lidselecter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import lidselecter.ModelItem;
import lidselecter.Sql_connect;

/**
 *
 * @author Aaik
 */
public class Toernooi_Eliminatie2 extends javax.swing.JFrame {

    DefaultListModel lijstModel = new DefaultListModel();

    int aantalSpelers;
    int whereClaus = 1;

    /**
     * Creates new form Eliminatie2
     */
    public Toernooi_Eliminatie2() {
        initComponents();
        DeelnemerLijst.setModel(lijstModel);
        vulSpelers();
        tellenSpelers();
        setLocationRelativeTo(null);

    }

    private void vulSpelers() {
        try {
            Sql_connect.doConnect();
            PreparedStatement stat1 = Sql_connect.getConnection().prepareStatement("select t.Id_persoon, t.Positie, p.voornaam, p.achternaam, t.Tafel_code from toernooideelnemer t join persoon p on t.Id_persoon = p.Id_persoon where Id_toernooi = ? AND t.Positie = 0 ORDER BY RAND()");
            stat1.setInt(1, whereClaus);
            ResultSet result1 = stat1.executeQuery();

            while (result1.next()) {
                ModelItem item = new ModelItem();
                item.id = result1.getInt("t.Id_persoon");
                item.voornaam = result1.getString("p.voornaam");
                item.achternaam = result1.getString("p.achternaam");
                item.positie = result1.getString("t.Positie");
                item.idTafel = result1.getString("t.Tafel_code");
                lijstModel.addElement(item);
            }
        } catch (Exception e) {
            ePopup(e);
        }
    }

    private void tellenSpelers() {
        try {
            Sql_connect.doConnect();

            PreparedStatement stat1 = Sql_connect.getConnection().prepareStatement("select count(*) as count from toernooideelnemer WHERE Id_toernooi = ? AND Positie = 0");
            stat1.setInt(1, whereClaus);
            ResultSet result1 = stat1.executeQuery();

            while (result1.next()) {
                ModelItem item = new ModelItem();
                item.positie = result1.getString("count");
                lijstModel.addElement(item);
                TXTlaagsteRating.setText(item.positie);
            }
            //vulLijst();
        } catch (Exception e) {
            ePopup(e);
        }
    }

    private void ePopup(Exception e) {
        final String eMessage = "Er is iets fout gegaan, neem contact op met de aplicatiebouwer, geef deze foutmelding door: ";
        String error = eMessage + e;
        JOptionPane.showMessageDialog(rootPane, error);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idToernooiTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DeelnemerLijst = new javax.swing.JList();
        TXTspelerId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TXTlaagsteRating = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        MELDINGFIELD = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Toernooi:");

        idToernooiTxt.setText("1");
        idToernooiTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idToernooiTxtActionPerformed(evt);
            }
        });

        DeelnemerLijst.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        DeelnemerLijst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                DeelnemerLijstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(DeelnemerLijst);

        jLabel1.setText("Speler id");

        jLabel2.setText("Uitschakelen met positie");

        jButton2.setText("wijzigen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addComponent(idToernooiTxt))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTspelerId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(TXTlaagsteRating, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idToernooiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXTspelerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TXTlaagsteRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addContainerGap())
        );

        MELDINGFIELD.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jButton1.setText("niet werkende terug button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(MELDINGFIELD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MELDINGFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DeelnemerLijstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_DeelnemerLijstValueChanged
        // TODO add your handling code here:
        gegevensLijst();

    }//GEN-LAST:event_DeelnemerLijstValueChanged

    private void idToernooiTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idToernooiTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idToernooiTxtActionPerformed

    private void gegevensLijst() {
        try {
            if (DeelnemerLijst.getSelectedValue() == null) {
                MELDINGFIELD.setText("Niks geselecteerd");

            } else {
                ModelItem selectedItem = (ModelItem) DeelnemerLijst.getSelectedValue();
                TXTspelerId.setText(Integer.toString(selectedItem.id));

                MELDINGFIELD.setText("Opvragen speler gelukt");
            }
        } catch (Exception e) {
            MELDINGFIELD.setText("Niks geselecteerd");

        }
    }

    private void update() {
        try {
            int idPersoon = Integer.parseInt(TXTspelerId.getText());
            int positie = Integer.parseInt(TXTlaagsteRating.getText());

            Sql_connect.doConnect();
            //int whereClaus = Integer.parseInt(idToernooiTxt.getText());

            PreparedStatement stat2 = Sql_connect.getConnection().prepareStatement("UPDATE toernooideelnemer SET Positie = ? WHERE Id_persoon = ? AND Id_toernooi= ?");
            stat2.setInt(1, positie);
            stat2.setInt(2, idPersoon);
            stat2.setInt(3, whereClaus);
            stat2.executeUpdate();
            
            PreparedStatement spelerAanwezigDown = Sql_connect.getConnection().prepareStatement("UPDATE tafel set spelerAanwezig=spelerAanwezig-1 where tafel_code = 1 AND Id_toernooi ?");
            //spelerAanwezigDown.setInt(1, tafelCode);
            spelerAanwezigDown.setInt(2, whereClaus);

            JOptionPane.showMessageDialog(rootPane, "Speler " + idPersoon + " is uitgechakeld en heeft rating " + positie + " meegekregen");
            Toernooi_Eliminatie2 Eliminatie2 = new Toernooi_Eliminatie2();
            Eliminatie2.setVisible(rootPaneCheckingEnabled);
            this.dispose();
            

            //vulLijst();
        } catch (Exception e) {
            ePopup(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toernooi_Eliminatie2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toernooi_Eliminatie2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toernooi_Eliminatie2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toernooi_Eliminatie2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toernooi_Eliminatie2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList DeelnemerLijst;
    private javax.swing.JLabel MELDINGFIELD;
    private javax.swing.JTextField TXTlaagsteRating;
    private javax.swing.JTextField TXTspelerId;
    private javax.swing.JTextField idToernooiTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
